name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Noodles.Dashboard/Noodles.Dashboard/Noodles.Dashboard.csproj
    
    - name: Build
      run: dotnet build Noodles.Dashboard/Noodles.Dashboard/Noodles.Dashboard.csproj --no-restore --configuration Release
    
    - name: Publish
      run: dotnet publish Noodles.Dashboard/Noodles.Dashboard/Noodles.Dashboard.csproj --no-build --configuration Release --output ./publish
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish 